# Uncomment this line to define a global platform for all pods
platform :osx, '10.14'

# CocoaPods dependencies for Flutter macOS plugins
plugin_pods

# Darwin (macOS) specific configuration
darwin_configs
